# 001: EarlySign Tutorial: Group Sequential Testing (Two-Proportions) with a Ledger-Centric Design

This tutorial demonstrates how to run a group sequential test (GST) for a two-proportions A/B experiment using a **ledger-centric** architecture.

We will:
1. Initialize a Polars-backed ledger.
2. Iteratively append observation batches (simulated).
3. Update a Wald Z statistic and a Lan–DeMets (OBF/Pocock) boundary per look.
4. Emit a stop signal if the boundary is crossed.
5. Summarize and visualize progress.

## Requirements

```bash
pip install earlysign[examples]
```

In [1]:
import numpy as np

# New business-oriented facade API - all A/B testing functionality in one place
from earlysign.api.ab_test import interim_analysis
from earlysign.runtime.runners import SequentialRunner
import ibis

from earlysign.core.ledger import Ledger
from earlysign.test_util import create_test_connection

from earlysign.core.components import Namespace
from earlysign.stats.schemes.two_proportions.group_sequential import (
    WaldZStatistic,
    LanDeMetsBoundary,
    PeekSignaler,
)
from earlysign.reporting.generic import LedgerReporter
from earlysign.reporting.two_proportions import TwoPropGSTReporter

np.set_printoptions(suppress=True)

## Configure the experiment

We plan 4 looks, a two-sided alpha of 0.05, and O'Brien–Fleming (OBF) spending. We also specify a target fixed-sample size per arm just for this simulation example.

In [2]:
import math
from datetime import datetime, timezone

# Experiment configuration
exp_id = "exp#loop-demo"
alpha_total = 0.05
looks = 4
spending = "conservative"  # "conservative" (OBF) or "aggressive" (Pocock)

# Step 1: Create a business-oriented experiment using the facade API
# This uses familiar terminology: "interim_analysis" instead of "group_sequential_test"
experiment = interim_analysis(
    experiment_id=exp_id, alpha=alpha_total, looks=looks, spending=spending
)

# Step 2: Create a runner with your chosen backend
# The runner handles execution while the module defines the experiment
conn = create_test_connection()  # Use DuckDB instead of Polars
ledger = Ledger(conn, exp_id)
runner = SequentialRunner(experiment, ledger)

print(f"📦 Experiment: {experiment.__class__.__name__}")
print(f"🏃 Runner: {runner.__class__.__name__}")
print(f"⚙️  Backend: {type(runner._ledger).__name__}")

# Simulation parameters (for demonstration)
n_per_arm = 400
t_grid = tuple((i + 1) / looks for i in range(looks))  # (0.25, 0.5, 0.75, 1.0)
targets = [math.ceil(n_per_arm * t) for t in t_grid]

# Ground-truth rates (for simulation)
pA_true, pB_true = 0.70, 0.80
rng = np.random.default_rng(7)

print(f"\n🎯 Experiment Design:")
print(f"   Method: Interim Analysis with {spending} spending")
print(f"   Alpha: {alpha_total}, Looks: {looks}")
print(f"   Targets per look: {targets}")
print(f"   True rates: Group A = {pA_true:.0%}, Group B = {pB_true:.0%}")

# The experiment automatically registers the design when setup() is called by the runner
summary = runner.get_summary()
print(f"\n✅ Setup complete. Components: {summary['components']}")

📦 Experiment: TwoPropGSTTemplate
🏃 Runner: SequentialRunner
⚙️  Backend: Ledger

🎯 Experiment Design:
   Method: Interim Analysis with conservative spending
   Alpha: 0.05, Looks: 4
   Targets per look: [100, 200, 300, 400]
   True rates: Group A = 70%, Group B = 80%

✅ Setup complete. Components: ['observation', 'statistic', 'criteria', 'signaler']

## Run the sequential procedure in a loop

For each look:
1. Append a new observation batch to the ledger.
2. Update the Wald Z statistic.
3. Update the Lan–DeMets (OBF) boundary at the current information fraction.
4. Let the signaler check whether to **stop early**.

In [3]:
cum_nA = cum_nB = cum_mA = cum_mB = 0
stopped = False
stop_look = None

for i, t in enumerate(t_grid, start=1):
    # Target sample size up to this look
    target = targets[i - 1]
    add_nA = max(target - cum_nA, 0)
    add_nB = max(target - cum_nB, 0)
    add_mA = int(rng.binomial(add_nA, pA_true)) if add_nA > 0 else 0
    add_mB = int(rng.binomial(add_nB, pB_true)) if add_nB > 0 else 0

    cum_nA += add_nA
    cum_nB += add_nB
    cum_mA += add_mA
    cum_mB += add_mB

    print(f"\n=== Look {i} ===")
    print(f"Adding: Group A {add_mA}/{add_nA}, Group B {add_mB}/{add_nB}")
    print(
        f"Cumulative: Group A {cum_mA}/{cum_nA} ({cum_mA/cum_nA:.1%}), Group B {cum_mB}/{cum_nB} ({cum_mB/cum_nB:.1%})"
    )

    # 1) Add observations using the modular interface
    runner.add_observations(
        group_a_success=add_mA,
        group_a_total=add_nA,
        group_b_success=add_mB,
        group_b_total=add_nB,
    )

    # 2) Run analysis - the module coordinates all components internally
    result = runner.analyze()

    print(f"Z-statistic: {result.statistic_value:.3f}")
    if result.threshold_value:
        print(f"Boundary: ±{result.threshold_value:.3f}")

    # Handle information_fraction formatting safely
    info_frac = result.additional_metrics.get("information_fraction", "N/A")
    if isinstance(info_frac, str):
        print(f"Information fraction: {info_frac}")
    else:
        print(f"Information fraction: {info_frac:.3f}")

    print(f"Decision: {'🛑 STOP' if result.should_stop else '✅ Continue'}")

    if result.should_stop:
        stopped = True
        stop_look = i
        break

print(f"\n=== Final Result ===")
print(f"Stopped: {stopped}, Stop look: {stop_look}")
print(f"Final sample size: {cum_nA + cum_nB}")

# Get final summary from the runner
final_summary = runner.get_summary()
print(f"Total looks executed: {final_summary['total_looks']}")

# Access the underlying ledger for advanced operations (if needed)
L = runner._ledger

=== Look 1 ===
Adding: Group A 64/100, Group B 82/100
Cumulative: Group A 64/100 (64.0%), Group B 82/100 (82.0%)
Z-statistic: 0.000
Information fraction: N/A
Decision: ✅ Continue

=== Look 2 ===
Adding: Group A 77/100, Group B 80/100
Cumulative: Group A 141/200 (70.5%), Group B 162/200 (81.0%)
Z-statistic: 0.000
Information fraction: N/A
Decision: ✅ Continue

=== Look 3 ===
Adding: Group A 66/100, Group B 83/100
Cumulative: Group A 207/300 (69.0%), Group B 245/300 (81.7%)
Z-statistic: 0.000
Information fraction: N/A
Decision: ✅ Continue

=== Look 4 ===
Adding: Group A 74/100, Group B 80/100
Cumulative: Group A 281/400 (70.2%), Group B 325/400 (81.2%)
Z-statistic: 0.000
Information fraction: N/A
Decision: ✅ Continue

=== Final Result ===
Stopped: False, Stop look: None
Final sample size: 800
Total looks executed: 4

## Inspect the ledger
We can show a generic view of the ledger and a method-specific progress table.

In [4]:
from IPython.display import display

gen = LedgerReporter(L)  # Pass the Ledger object directly
gen_table = gen.ledger_table().execute()  # Execute to get actual data
gen_counts = (
    gen.namespace_kind_counts().execute()
)  # Use correct method name and execute
display(gen_table)
display(gen_counts)

,uuid,ts,payload_type,labels,payload
0,1baa1fdf954e487e9bf2e6d5d8e43215,2025-09-15T16:56:28.236435+00:00,gst_design,"{'experiment_id': 'exp#loop-demo', 'kind': 'ex...","{'alpha_total': 0.05, 'looks': 4, 'method': 'g..."
1,b78f4ee080f3491fa23a4a508fad631c,2025-09-15T16:56:28.521872+00:00,TwoPropObsBatch,"{'experiment_id': 'exp#loop-demo', 'kind': 'ob...","{'mA': 64, 'mB': 82, 'nA': 100, 'nB': 100}"
2,880863c176214ae4aa8036a8df46ee71,2025-09-15T16:56:28.536791+00:00,WaldZ,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'mA': 64, 'mB': 82, 'nA': 100, 'nB': 100, 'pA..."
3,e44f53f2927549ddae7a1f0be5421170,2025-09-15T16:56:28.542466+00:00,GSTBoundary,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'alpha_i': 0.05, 'info_time': 1.0, 'lower': -..."
4,65591ab0a4e64c959b110cefbd9edb5e,2025-09-15T16:56:28.557992+00:00,dict,"{'experiment_id': 'exp#loop-demo', 'kind': 'de...","{'action': 'stop', 'pA_hat': 0.64, 'pB_hat': 0..."
5,3ff1b20329a342638147831b55ca04f0,2025-09-15T16:56:28.576164+00:00,TwoPropObsBatch,"{'experiment_id': 'exp#loop-demo', 'kind': 'ob...","{'mA': 77, 'mB': 80, 'nA': 100, 'nB': 100}"
6,978b8248fbf84cc5af236cbe5be9cb27,2025-09-15T16:56:28.583702+00:00,WaldZ,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'mA': 141, 'mB': 162, 'nA': 200, 'nB': 200, '..."
7,47ad07949e7b4ee1a884ed9f211bc0c7,2025-09-15T16:56:28.588481+00:00,GSTBoundary,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'alpha_i': 0.05, 'info_time': 1.0, 'lower': -..."
8,6e9c2400ae40415c905015f157048320,2025-09-15T16:56:28.601447+00:00,dict,"{'experiment_id': 'exp#loop-demo', 'kind': 'de...","{'action': 'stop', 'pA_hat': 0.705, 'pB_hat': ..."
9,9350ec9fb5fc4713805d5310c485c8f6,2025-09-15T16:56:28.619223+00:00,TwoPropObsBatch,"{'experiment_id': 'exp#loop-demo', 'kind': 'ob...","{'mA': 66, 'mB': 83, 'nA': 100, 'nB': 100}"
10,0428fdd06f104de7b6839312593ce288,2025-09-15T16:56:28.627372+00:00,WaldZ,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'mA': 207, 'mB': 245, 'nA': 300, 'nB': 300, '..."
11,a18ea644babe430c82ef0574a3561274,2025-09-15T16:56:28.632265+00:00,GSTBoundary,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'alpha_i': 0.05, 'info_time': 1.0, 'lower': -..."
12,b0ca0d60dcab440cb963a438939f642d,2025-09-15T16:56:28.644946+00:00,dict,"{'experiment_id': 'exp#loop-demo', 'kind': 'de...","{'action': 'stop', 'pA_hat': 0.69, 'pB_hat': 0..."
13,492002cb2e8841e1a6f594dc16d8ff6e,2025-09-15T16:56:28.661599+00:00,TwoPropObsBatch,"{'experiment_id': 'exp#loop-demo', 'kind': 'ob...","{'mA': 74, 'mB': 80, 'nA': 100, 'nB': 100}"
14,beb59f6ced0d4a1fb896c94395bff96f,2025-09-15T16:56:28.668350+00:00,WaldZ,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'mA': 281, 'mB': 325, 'nA': 400, 'nB': 400, '..."
15,accee8fe0409466c93b2c79a41151c8d,2025-09-15T16:56:28.672409+00:00,GSTBoundary,"{'experiment_id': 'exp#loop-demo', 'kind': 'up...","{'alpha_i': 0.05, 'info_time': 1.0, 'lower': -..."
16,4883cd3dde024cf99203e55ee3145303,2025-09-15T16:56:28.684862+00:00,dict,"{'experiment_id': 'exp#loop-demo', 'kind': 'de...","{'action': 'stop', 'pA_hat': 0.7025, 'pB_hat':..."

  namespace               kind  count
0  criteria            updated      4
1    design  experiment_design      1
2       obs        observation      4
3   signals           decision      4
4     stats            updated      4

In [5]:
rep = TwoPropGSTReporter(L)  # Pass Ledger object directly
rep.progress_table()

,ts,"JSONGetItem(labels, 'entity')",look,time_index,z,nA,nB,mA,mB,time_index_right,upper,lower,t
0,2025-09-15T16:56:28.536791+00:00,None,0,None,2.927700,100,100,64,82,None,NaN,NaN,NaN
1,2025-09-15T16:56:28.583702+00:00,None,0,None,2.468454,200,200,141,162,None,NaN,NaN,NaN
2,2025-09-15T16:56:28.627372+00:00,None,0,None,3.638294,300,300,207,245,None,NaN,NaN,NaN
3,2025-09-15T16:56:28.668350+00:00,None,0,None,3.659874,400,400,281,325,None,NaN,NaN,NaN

In [6]:
# table.select(table.labels["namespace"].str).execute() == Namespace.CRITERIA.value
# # Namespace.STATS.value
# stats_filtered = table.filter(
#     (table.labels["namespace"].str == Namespace.STATS.value)
#     & (table.labels["kind"].str == "updated")
#     & (table.payload_type == "WaldZ")
# )
# stats_filtered.execute()

## Visualize Z and boundaries
A simple plot of the Wald Z trajectory and the symmetric boundaries across information fractions.

In [7]:
# If running in a notebook, this will render inline
rep.plot()

{'ts': '2025-09-15T16:56:28.536791+00:00', "JSONGetItem(labels, 'entity')": None, 'look': 0, 'time_index': None, 'z': 2.9277002188455983, 'nA': 100, 'nB': 100, 'mA': 64, 'mB': 82, 'time_index_right': None, 'upper': nan, 'lower': nan, 't': nan}
{'ts': '2025-09-15T16:56:28.583702+00:00', "JSONGetItem(labels, 'entity')": None, 'look': 0, 'time_index': None, 'z': 2.4684538174137822, 'nA': 200, 'nB': 200, 'mA': 141, 'mB': 162, 'time_index_right': None, 'upper': nan, 'lower': nan, 't': nan}
{'ts': '2025-09-15T16:56:28.627372+00:00', "JSONGetItem(labels, 'entity')": None, 'look': 0, 'time_index': None, 'z': 3.638293754762681, 'nA': 300, 'nB': 300, 'mA': 207, 'mB': 245, 'time_index_right': None, 'upper': nan, 'lower': nan, 't': nan}
{'ts': '2025-09-15T16:56:28.668350+00:00', "JSONGetItem(labels, 'entity')": None, 'look': 0, 'time_index': None, 'z': 3.6598742450249606, 'nA': 400, 'nB': 400, 'mA': 281, 'mB': 325, 'time_index_right': None, 'upper': nan, 'lower': nan, 't': nan}

ValueError: Information time t must be in (0, 1], got nan

## Next steps
- Replace the simulated observation batches with your actual data source.
- Swap OBF with Pocock spending by setting `style="pocock"`.
- Extend the scheme to other data types or add additional criteria/signals.
- Persist the Polars ledger using sinks/sources in `earlysign.backends.polars.io`.

## Advanced: Creating Custom Experiment Modules

The modular architecture makes it easy to create **portable, shareable experiment definitions**. Here's how to create your own custom modules:

### 1. Custom Module Definition
Analysts can create their own modules by subclassing `ExperimentTemplate` or `TwoPropTemplate`

### 2. Data Ingestion Components
For complex data scenarios, you can still access the underlying ingestion components

### 3. Module Comparison
Compare different experiment designs using the `BatchRunner`